name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tag: [pspdev/pspdev]

    container: ${{ matrix.docker_tag }}:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add build-base git bash
    

    - name: Compile project
      run: |
        make clean all

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
    
    - name: Sanitized Docker Tag
      id: docker_tag
      run: echo "sha8=$(echo ${{matrix.docker_tag}} | sed s:/:__:g)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: hello-${{ steps.slug.outputs.sha8 }}-${{ steps.docker_tag.outputs.sha8 }}
        path: |
          hello.elf 
          EBOOT.PBP 
          PARAM.SFO
          dump.txt
